hchanhi/Am2zing_GodGong_Project

frontend/src/App.js
frontend/src/Header.js
frontend/src/Join.js
frontend/src/Login.js
frontend/src/join.css

[modify]/modify join, login page

[modify]/modify join, login page

---

frontend/package.json
frontend/src/App.js
frontend/src/Join.js

[modify]/modify join

---

frontend/package-lock.json
frontend/package.json
frontend/src/setupProxy.js
src/main/java/com/gg/service/DiaryService.java

[modify]/DiaryService 수정

---

frontend/src/Join.js
frontend/src/Login.js
frontend/src/Todo/TodoStudy.js
frontend/src/logintest.js

[modify] modify login

---

frontend/src/Join.js
frontend/src/Login.js

[modify]/add token

---

frontend/src/App.js
frontend/src/Diary.js
frontend/src/Home.js
frontend/src/diary.css

[add]/ add diary

---

frontend/src/Diary.js
frontend/src/diary.css

[add] add diary axios

---

frontend/src/Diary.js

[modify]modify diary content

---

frontend/src/Diary.js

[modify] modify diary editor

---

frontend/package-lock.json
src/main/java/com/gg/controller/DiaryController.java

[modify]/DiaryController 수정. Body로 변수를 받아야함..

[modify]/DiaryController 수정. Body로 변수를 받아야함..

---

frontend/src/Diary.js
src/main/java/com/gg/controller/DiaryController.java

[modify]/Diary.js 콘솔창 수정

---

frontend/src/Diary.js

[modify]modify navigate link

---

frontend/src/App.js
frontend/src/DiaryList.js
frontend/src/MyPage.js

[add]/ add mypage, diaryList

---

src/main/java/com/gg/controller/MypageController.java
src/main/java/com/gg/domain/Diary.java
src/main/java/com/gg/repository/StudylogRepository.java
src/main/java/com/gg/service/DiaryService.java
src/main/java/com/gg/service/MypageService.java

[modify]/특정날짜 공부시간 메소드 추가

---

frontend/src/Diary.js
frontend/src/DiaryList.js
frontend/src/components/DiaryButton.js
frontend/src/components/DiaryCom.js
frontend/src/diary.css

[add]/add diary list

---

src/main/java/com/gg/repository/StudylogRepository.java
src/main/java/com/gg/service/StudylogService.java

[modyfy]/Studylog 메소드이름 오류 수정

---

frontend/src/DiaryList.js

[modify]/modify date

---

src/main/java/com/gg/controller/RoomController.java
src/main/java/com/gg/domain/Room.java
src/main/java/com/gg/service/RoomService.java

[add] create room / room list

---

frontend/src/DiaryList.js

[add]/add loading 추가

---

src/main/java/com/gg/controller/TodoController.java
src/main/java/com/gg/domain/Todo.java
src/main/java/com/gg/repository/TodoRepository.java
src/main/java/com/gg/service/DiaryService.java
src/main/java/com/gg/service/TodoService.java

[add]TodoService, TodoController 추가

[add]TodoService, TodoController 추가

---

frontend/src/DiaryList.js
frontend/src/components/DiaryCom.js

[add]/add Sentiment

---

src/main/java/com/gg/repository/TodoRepository.java
src/main/java/com/gg/service/TodoService.java

[modyfi]/Todo 오타수정

---

frontend/src/DiaryList.js
frontend/src/MyPage.js

[modify]modify error

---

frontend/src/DiaryList.js
frontend/src/components/DiaryCom.js

[add]/ add state

---

frontend/src/App.js
frontend/src/DiaryDetail.js
frontend/src/components/DiaryCom.js

[add]/add diary edit

---

frontend/src/components/DiaryCom.js

[modify]modify modify button

---

frontend/src/App.js
frontend/src/components/DiaryCom.js
frontend/src/diary.css
frontend/src/user.js

[add]/add user page

---

frontend/src/App.js
frontend/src/Diary.js
frontend/src/DiaryDetail.js
frontend/src/components/DiaryCom.js

[modify]/ modify diary edit url

[modify]/ modify diary edit url

---

frontend/src/DiaryDetail.js
frontend/src/user.js

[modify] modify date

---

frontend/src/Diary.js
frontend/src/DiaryDetail.js
frontend/src/diary.css
frontend/src/user.js

[modify]/modify user, diary css

[modify]/modify user, diary css

---

frontend/src/user.js
src/main/java/com/gg/config/SecurityConfig.java
src/main/java/com/gg/controller/UserController.java
src/main/java/com/gg/service/UserService.java

[modyfy]/회원정보수정 디버깅중

---

frontend/src/user.js

[modify]/modify user

---

frontend/src/Challenge.js
src/main/java/com/gg/controller/UserController.java
src/main/java/com/gg/service/UserService.java

[modyfy]회원정보수정

---

frontend/src/user.js

[modify]/modify user password

---

frontend/src/user.js

[modify]/ modify password alert

[modify]/ modify password alert

---

frontend/src/Challenge.js
frontend/src/ChallengeModal.js
frontend/src/user.js

[modyfy]/challenge 자리비움시 시간증가x

[modyfy]/challenge 자리비움시 시간증가x

---

frontend/src/Challenge.js
src/main/java/com/gg/controller/DiaryController.java
src/main/java/com/gg/controller/RoomController.java
src/main/java/com/gg/controller/StudylogController.java
src/main/java/com/gg/repository/DiaryRepository.java
src/main/java/com/gg/repository/RoomRepository.java
src/main/java/com/gg/repository/StudylogRepository.java
src/main/java/com/gg/service/DiaryService.java
src/main/java/com/gg/service/RoomService.java
src/main/java/com/gg/service/StudylogService.java

[add]/메인페이지용 메소드들 추가

---

frontend/src/Join.js
frontend/src/diary.css
frontend/src/user.js

[add]/add check, user delete

---

frontend/src/App.js
frontend/src/Diary.js
frontend/src/DiaryDetail.js
frontend/src/DiaryList.css
frontend/src/DiaryList.js
frontend/src/FindPassword.js
frontend/src/Login.js
frontend/src/MyPage.js
frontend/src/components/DiaryCom.js
frontend/src/user.js

[add]/ add findpassword page & modify css

[add]/ add findpassword page & modify css

---

frontend/src/App.js
frontend/src/DiaryList.css
frontend/src/DiaryList.js
frontend/src/EditPassword.js
frontend/src/diary.css
frontend/src/join.css
frontend/src/user.js

[add]/ add editpassword page

---

frontend/src/Challenge.js
src/main/java/com/gg/controller/StudylogController.java
src/main/java/com/gg/repository/StudylogRepository.java
src/main/java/com/gg/service/StudylogService.java

[modify]/모달에 시간초 뜸

---

src/main/java/com/gg/controller/DiaryController.java

[modify]/일기삭제 디버깅

---

frontend/src/FindPassword.js
frontend/src/FindPw.js

[modify]/ modify conflict

---

frontend/src/User.css
frontend/src/user.js

[modify] / modify user

---

frontend/src/Challenge.js

[modyfy]/처음부터캠안켰을때 시간증가 되던 오류 수정

[modyfy]/처음부터캠안켰을때 시간증가 되던 오류 수정

---

frontend/src/Diary.js
frontend/src/DiaryList.js
frontend/src/MyPage.js
frontend/src/Mypage.css
frontend/src/user.js

[modify]/ modify 마이페이지 컴포넌트로 나오게 수정

[modify]/ modify 마이페이지 컴포넌트로 나오게 수정

---

frontend/src/App.js
frontend/src/Login.js
frontend/src/MyPage.js

[modify]/modify 로그인창 영어 한글로 고침, 마이페이지 수정

[modify]/modify 로그인창 영어 한글로 고침, 마이페이지 수정

---

frontend/src/diary.css

[modify]/ modify 다이어리 리사이즈 못하게 막음

[modify]/ modify 다이어리 리사이즈 못하게 막음

---

frontend/src/Home.js

[add]/add 최근다이어리

---

frontend/src/Home.js

[modify]/modify 최신 다이어리 axios

---

frontend/src/Home.js

[add]/ add recent diary

---

frontend/src/DiaryList.css
frontend/src/Home.js
frontend/src/components/DiaryCom.js

[modify]/modify 다이어리 리스트에 엔터 구현

[modify]/modify 다이어리 리스트에 엔터 구현

---

src/main/java/com/gg/controller/RoomController.java
src/main/java/com/gg/controller/TodoController.java
src/main/java/com/gg/repository/RoomlogRepository.java
src/main/java/com/gg/repository/TodoRepository.java
src/main/java/com/gg/service/RoomlogService.java
src/main/java/com/gg/service/TodoService.java
src/main/resources/data.sql

[add] add ExitRoom, DeleteTodo

---

src/main/java/com/gg/repository/StudylogRepository.java

[modify]/랭킹 디버깅 완료

---

frontend/src/TimeCalendar.js

[modify]필요없는function제거

---

frontend/src/App.css
frontend/src/App.js
frontend/src/DiaryDetail.js
frontend/src/DiaryList.css
frontend/src/DiaryList.js
frontend/src/Home.css
frontend/src/Home.js
frontend/src/MyPage.js
frontend/src/Mypage.css
frontend/src/Pagination.js
frontend/src/components/DiaryCom.js

[add]/ add diary paging

---

frontend/package-lock.json
frontend/package.json
frontend/src/Challenge.js
frontend/src/Diary.js
frontend/src/DiaryDetail.js
frontend/src/DiaryList.css
frontend/src/DiaryList.js
frontend/src/Join.js
frontend/src/Login.js
frontend/src/join.css
frontend/src/user.js

[add]/add 얼럿창 디자인

---

frontend/src/Diary.js
frontend/src/DiaryDetail.js
frontend/src/DiaryList.js

.[modify]/ import Swal from 'sweetalert2' 수정

[modify]/ import Swal from 'sweetalert2' 수정

---

frontend/src/Diary.js
frontend/src/DiaryDetail.js

[modify]/ 다이어리 얼럿창 수정

---

src/main/java/com/gg/repository/RoomlogRepository.java

[fix] fix roomlog Exit

---

frontend/src/Diary.js
frontend/src/DiaryDetail.js
frontend/src/DiaryList.js
frontend/src/Join.js
frontend/src/Login.js
frontend/src/user.js

[modify]/ modify 얼럿

---

frontend/src/DiaryList.css
frontend/src/DiaryList.js
frontend/src/Home.js
frontend/src/Pagination.js
frontend/src/components/DiaryCom.js
frontend/src/diary.css

[modify]/ 그림자 수정

---

frontend/src/Home.js
frontend/src/MyPage.js
frontend/src/user.js

[modify]/ 마이페이지 일기를 기본으로

---

frontend/src/EditPassword.js
frontend/src/FindPassword.js
frontend/src/FindPw.js
frontend/src/MyPage.js
frontend/src/Todo/Chatting.js
frontend/src/Todo/CompleteTodo.js
frontend/src/Todo/DeleteTodoBtn.js
frontend/src/Todo/MakeTodo.js
frontend/src/Todo/MakeTodoStudy.js
frontend/src/Todo/TodoCard.js
frontend/src/Todo/TodoStudyRoom.js
frontend/src/Todo/chattingConnect.js
frontend/src/join.css

[modify]/ 전체 얼럿창 수정

---

frontend/src/User.css
frontend/src/diary.css

[modify]/ 유저 css 수정

---

frontend/src/Home.js

[modify]/랭킹 1,2,3등 메달표시

---

src/main/java/com/gg/controller/RoomController.java
src/main/java/com/gg/controller/StompChatController.java
src/main/java/com/gg/controller/TodoController.java
src/main/java/com/gg/service/RoomlogService.java
src/main/java/com/gg/service/TodoService.java

[modify] refactoring

---

frontend/src/DiaryList.css
frontend/src/EditPassword.js
frontend/src/FindPassword.js

[modify]/얼럿 수정

---

frontend/src/Login.js
frontend/src/MyTodoStudy.js
frontend/src/Todo/CompleteTodo.js
frontend/src/Todo/ExitStudyBtn.js
frontend/src/Todo/JoinStudyBtn.js
frontend/src/Todo/TodoCard.js
frontend/src/Todo/TodoStudyRoom.js

[modify]/ 전체 버튼색 통일

---

frontend/src/Todo/MakeTodo.js
frontend/src/Todo/MakeTodoStudy.js

[modify]/ 투두 버튼 색 수정

---

frontend/src/ChallengeModal.css

[modify]/ 챌린지 버튼 색 수정

---

frontend/src/Motion.js

Feat : 티쳐블 머신 재추가

---

src/main/java/com/gg/controller/AuthController.java
src/main/java/com/gg/controller/UserController.java
src/main/java/com/gg/util/RedisUtil.java

userController와 redisUtil에 있던 필요 없는 코드를 삭제 했습니다.

[refacor] 회원 코드 리팩토링

---

build.gradle

jwt 에러가 생겨 0.11.5 버전으로 업그레이드와 만료시간을 증가시킴

[Fix] jwt 0.11.5 버전으로 업그레이드
